FROM rust:1.89-alpine3.22 AS builder
RUN apk add --no-cache musl-dev make
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY crates/server/ crates/server/
COPY crates/cli/ crates/cli/
RUN cargo build --release -p notir-cli

FROM alpine:3.22
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/target/release/notir-cli /usr/local/bin/notir-cli
ENTRYPOINT ["notir-cli"]
